/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Streamer {
  constructor(options?: RuntimeResourceLimitsInput | undefined | null)
  startStream(options: StartStreamInput): Promise<StreamStatusOutput>
  getStatus(streamId: string): Promise<StreamStatusOutput>
  getStatuses(streamIds: Array<string>): Promise<Array<StreamStatusBatchItemOutput>>
  setNext(streamId: string, next?: TrackSourceInput | undefined | null): Promise<StreamStatusOutput>
  switchTrack(streamId: string, current: TrackSourceInput, next?: TrackSourceInput | undefined | null): Promise<StreamStatusOutput>
  refreshCurrentSource(streamId: string, current: TrackSourceInput): Promise<StreamStatusOutput>
  seekStream(streamId: string, seconds: number): Promise<StreamStatusOutput>
  setVolume(streamId: string, volume: number): Promise<StreamStatusOutput>
  setGain(streamId: string, gainDb: number): Promise<StreamStatusOutput>
  pauseStream(streamId: string): Promise<StreamStatusOutput>
  resumeStream(streamId: string): Promise<StreamStatusOutput>
  stopStream(streamId: string): Promise<StreamStatusOutput>
  drainEvents(streamId?: string | undefined | null): Array<StreamEventOutput>
  setEventCallback(callback?: ((arg: StreamEventOutput) => void) | undefined | null): void
  validateRtpTransportConfig(config: RtpTransportConfigInput): RtpTransportConfigOutput
  validateSourceResolverConfig(config: SourceResolverConfigInput): SourceResolverConfigOutput
  recommendReplayGain(input: ReplayGainInput): ReplayGainRecommendationOutput
  shutdown(): Promise<void>
}

export interface HttpLiveSourceConfigInput {
  openTimeoutMs?: number
  idleTimeoutMs?: number
  maxBufferedBytes?: number
  maxRetries?: number
  retryBackoffMs?: number
}

export interface HttpLiveSourceConfigOutput {
  openTimeoutMs: number
  idleTimeoutMs: number
  maxBufferedBytes: number
  maxRetries: number
  retryBackoffMs: number
}

export interface HttpSourceConfigInput {
  ioTimeoutMs?: number
  maxBytes?: number
  cacheTempFiles?: boolean
  maxRetries?: number
  retryBackoffMs?: number
}

export interface HttpSourceConfigOutput {
  ioTimeoutMs: number
  maxBytes: number
  cacheTempFiles: boolean
  maxRetries: number
  retryBackoffMs: number
}

export interface MediaBufferConfigInput {
  decodeBatchMs?: number
  encodedCapacityMs?: number
  prebufferMs?: number
  nextPrimeMs?: number
  maxPlayoutLatenessMs?: number
}

export interface ReplayGainInput {
  mode?: 'track' | 'album'
  trackGainDb?: number
  albumGainDb?: number
  trackPeak?: number
  albumPeak?: number
  preampDb?: number
  preventClipping?: boolean
  targetPeakDbfs?: number
  fallbackToOther?: boolean
}

export interface ReplayGainRecommendationOutput {
  source: 'track' | 'album'
  gainDb: number
  requestedGainDb: number
  clippingLimited: boolean
  rangeLimited: boolean
}

export interface RtcpReceiverReportOutput {
  reportsReceived: number
  senderSsrc: number
  sourceSsrc: number
  fractionLost: number
  fractionLostRatio: number
  fractionLostPercent: number
  totalLost: number
  lastSequenceNumber: number
  jitter: number
  jitterMicros: number
  jitterMs: number
  lastSenderReport: number
  delay: number
  roundTripTimeMicros?: number
  roundTripTimeMs?: number
}

export interface RtpEncryptionConfigInput {
  mode: string
  secretKey?: Buffer
}

export interface RtpTransportConfigInput {
  ip: string
  port: number
  rtcpPort?: number
  audioSsrc: number
  audioPt?: number
  bitrate?: number
  rtcpMux?: boolean
  rtpKeepaliveIntervalMs?: number
  mtu?: number
  localIp?: string
  localPort?: number
  encryption?: RtpEncryptionConfigInput
}

export interface RtpTransportConfigOutput {
  remoteIp: string
  remoteRtpPort: number
  remoteRtcpPort?: number
  localIp: string
  localRtpPort: number
  payloadType: number
  ssrc: number
  mtu: number
  rtcpMux: boolean
  opusBitrateBps?: number
  rtpKeepaliveIntervalMs?: number
  encryptionMode: string
}

export interface RuntimeResourceLimitsInput {
  maxStreams?: number
  maxCpuWorkers?: number
  maxBlockingProducers?: number
  maxBlockingPreloads?: number
  maxConcurrentHttpDownloads?: number
  maxConcurrentLiveStreams?: number
  maxLiveBufferedBytes?: number
  maxTempfileBytes?: number
}

export interface SourceResolverConfigInput {
  http?: HttpSourceConfigInput
  liveHttp?: HttpLiveSourceConfigInput
}

export interface SourceResolverConfigOutput {
  http: HttpSourceConfigOutput
  liveHttp: HttpLiveSourceConfigOutput
}

export interface StartStreamInput {
  streamId: string
  current: TrackSourceInput
  next?: TrackSourceInput
  transport: RtpTransportConfigInput
  source?: SourceResolverConfigInput
  buffer?: MediaBufferConfigInput
  volume?: number
  gainDb?: number
}

export interface StreamEventOutput {
  sequence: number
  type: 'streamStarted' | 'streamStopped' | 'stateChanged' | 'nextNeeded' | 'sourceRefreshNeeded' | 'networkQualityChanged' | 'error'
  streamId?: string
  trackId?: string
  sourceRole?: 'current' | 'next'
  quality?: 'good' | 'degraded' | 'poor'
  qualitySamples?: number
  latestLossPercent?: number
  averageLossPercent?: number
  maxLossPercent?: number
  averageJitterMs?: number
  maxJitterMs?: number
  averageRoundTripTimeMs?: number
  maxRoundTripTimeMs?: number
  code?: 'INVALID_SOURCE' | 'SOURCE_TIMEOUT' | 'SOURCE_AUTH_EXPIRED' | 'NOT_SEEKABLE' | 'DECODE_ERROR' | 'RESAMPLE_ERROR' | 'ENCODE_ERROR' | 'RTP_SEND_ERROR' | 'STREAM_CLOSED' | 'BUSY' | 'INTERNAL' | 'STREAM_NOT_FOUND' | 'STREAM_ALREADY_EXISTS' | 'INVALID_CONFIG' | 'UNSUPPORTED'
  message?: string
  status?: StreamStatusOutput
}

export interface StreamStatusBatchItemOutput {
  streamId: string
  ok: boolean
  status?: StreamStatusOutput
  code?: 'INVALID_SOURCE' | 'SOURCE_TIMEOUT' | 'SOURCE_AUTH_EXPIRED' | 'NOT_SEEKABLE' | 'DECODE_ERROR' | 'RESAMPLE_ERROR' | 'ENCODE_ERROR' | 'RTP_SEND_ERROR' | 'STREAM_CLOSED' | 'BUSY' | 'INTERNAL' | 'STREAM_NOT_FOUND' | 'STREAM_ALREADY_EXISTS' | 'INVALID_CONFIG' | 'UNSUPPORTED'
  message?: string
}

export interface StreamStatusOutput {
  streamId: string
  current?: TrackSourceOutput
  next?: TrackSourceOutput
  playState: 'idle' | 'buffering' | 'playing' | 'paused' | 'stopped'
  timePlayedMs: number
  generation: number
  volume: number
  gainDb: number
  receiverReport?: RtcpReceiverReportOutput
}

export interface TrackSourceInput {
  id: string
  kind: 'file' | 'url' | 'live'
  url?: string
  path?: string
  formatHint?: string
  seekable?: boolean
  headers?: Record<string, string>
}

export interface TrackSourceOutput {
  id: string
  kind: 'file' | 'url' | 'live'
  formatHint?: string
  seekable?: boolean
}
